App: # APP基础设置项
  RunMode: debug
  AttachmentIncomeRate: 0.8
  MaxCommentCount: 1000
  MaxWhisperDaily: 1000       # 一天可以发送的最大私信总数，临时措施，后续将去掉这个限制
  MaxCaptchaTimes: 2          # 最大获取captcha的次数
  DefaultContextTimeout: 60
  DefaultPageSize: 10
  MaxPageSize: 100
Cache:
  KeyPoolSize: 256            # 键的池大小， 设置范围[128, ++], 默认256
  CientSideCacheExpire: 60    # 客户端缓存过期时间 默认60s
  UnreadMsgExpire: 60         # 未读消息过期时间，单位秒， 默认60s
  UserTweetsExpire: 60        # 获取用户推文列表过期时间，单位秒， 默认60s
  IndexTweetsExpire: 120      # 获取广场推文列表过期时间，单位秒， 默认120s
  TweetCommentsExpire: 120    # 获取推文评论过期时间，单位秒， 默认120s
  IndexTrendsExpire: 120      # 获取广场动态信息过期时间，单位秒， 默认120s
  OnlineUserExpire: 300       # 标记在线用户 过期时间，单位秒， 默认300s
  UserInfoExpire: 120         # 获取用户信息过期时间，单位秒， 默认120s
  UserProfileExpire: 120      # 获取用户概要过期时间，单位秒， 默认120s
  UserRelationExpire: 120     # 用户关系信息过期时间，单位秒， 默认120s
  MessagesExpire: 60          # 消息列表过期时间，单位秒， 默认60s
EventManager: # 事件管理器的配置参数
  MinWorker: 64               # 最小后台工作者, 设置范围[5, ++], 默认64
  MaxEventBuf: 128            # 最大log缓存条数, 设置范围[10, ++], 默认128
  MaxTempEventBuf: 256        # 最大log缓存条数, 设置范围[10, ++], 默认256
  MaxTickCount: 60            # 最大的循环周期, 设置范围[60, ++], 默认60
  TickWaitTime: 1             # 一个周期的等待时间，单位：秒 默认1s
MetricManager: # 指标监控管理器的配置参数
  MinWorker: 32               # 最小后台工作者, 设置范围[5, ++], 默认32
  MaxEventBuf: 128            # 最大log缓存条数, 设置范围[10, ++], 默认128
  MaxTempEventBuf: 256        # 最大log缓存条数, 设置范围[10, ++], 默认256
  MaxTickCount: 60            # 最大的循环周期, 设置范围[60, ++], 默认60
  TickWaitTime: 1             # 一个周期的等待时间，单位：秒 默认1s
JobManager: # Cron Job理器的配置参数
  MaxOnlineInterval: "@every 5m"       # 更新最大在线人数，默认每5分钟更新一次
  UpdateMetricsInterval: "@every 5m"   # 更新Prometheus指标，默认每5分钟更新一次
Features:
  Default: []
WebServer: # Web服务
  RunMode: debug
  HttpIp: 127.0.0.1
  HttpPort: 8008
  ReadTimeout: 60
  WriteTimeout: 60
PprofServer: # Pprof服务
  RunMode: debug
  HttpIp: 127.0.0.1
  HttpPort: 6060
  ReadTimeout: 60
  WriteTimeout: 60
CacheIndex:
  MaxUpdateQPS: 100             # 最大添加/删除/更新Post的QPS, 设置范围[10, 10000], 默认100
SimpleCacheIndex: # 缓存泡泡广场消息流
  MaxIndexSize: 200             # 最大缓存条数
  CheckTickDuration: 60         # 循环自检查每多少秒一次
  ExpireTickDuration: 300       # 每多少秒后强制过期缓存, 设置为0禁止强制使缓存过期
BigCacheIndex: # 使用BigCache缓存泡泡广场消息流
  MaxIndexPage: 1024            # 最大缓存页数，必须是2^n, 代表最大同时缓存多少页数据
  HardMaxCacheSize: 256         # 最大缓存大小(MB)，0表示无限制
  Verbose: False                # 是否打印cache操作的log
  ExpireInSecond: 300           # 多少秒(>0)后强制过期缓存
RedisCacheIndex: # 使用Redis缓存泡泡广场消息流
  Verbose: False                # 是否打印cache操作的log
  ExpireInSecond: 300           # 多少秒(>0)后强制过期缓存
Pyroscope: # Pyroscope配置
  AppName: "paopao-ce"                # application name
  Endpoint: "http://localhost:4040"   # Pyroscope server address
  AuthToken:                          # Pyroscope authentication token
  Logger:  none                       # Pyroscope logger (standard | logrus | none)
Logger: # 日志通用配置
  Level: debug # 日志级别 panic|fatal|error|warn|info|debug|trace
LoggerFile: # 使用File写日志
  SavePath: custom/data/paopao-ce/logs
  FileName: app
  FileExt: .log
LoggerMeili: # 使用Meili写日志
  Host: meili:7700
  Index: paopao-log
  ApiKey: paopao-meilisearch
  Secure: False
  MinWorker: 5               # 最小后台工作者, 设置范围[5, 100], 默认5
  MaxLogBuffer: 100          # 最大log缓存条数, 设置范围[10, 10000], 默认100
JWT: # 鉴权加密
  Secret: 18a6413dc4fe394c66345ebe501b2f26
  Issuer: paopao-api
  Expire: 86400
TweetSearch: # 推文关键字搜索相关配置
  MaxUpdateQPS: 100            # 最大添加/删除/更新Post的QPS，设置范围[10, 10000], 默认100
  MinWorker: 10                # 最小后台更新工作者, 设置范围[5, 1000], 默认10
Meili: # Meili搜索配置
  Host: meili:7700
  Index: paopao-data
  ApiKey: paopao-meilisearch
  Secure: False
ObjectStorage: # 对象存储通用配置
  RetainInDays: 2   # 临时对象过期时间多少天
  TempDir: tmp      # 临时对象存放目录名
MinIO: # MinIO 存储配置
  AccessKey: Q3AM3UQ867SPQQA43P2F
  SecretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  Secure: False
  Endpoint: minio:9000
  Bucket: paopao
  Domain: 127.0.0.1:9000
Database: # Database通用配置
  LogLevel: error   # 日志级别 silent|error|warn|info
  TablePrefix: p_   # 表名前缀
MySQL: # MySQL数据库
  Username: paopao
  Password: paopao
  Host: db:3306
  DBName: paopao
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  InitAddress:
  - redis:6379
  Username:
  Password:
  SelectDB:
  ConnWriteTimeout: 60   # 连接写超时时间 多少秒 默认 60秒
WebProfile:
  UseFriendship: true              # 前端是否使用好友体系
  EnableTrendsBar: true            # 广场页面是否开启动态条栏功能
  AllowTweetAttachment: true       # 是否允许推文附件
  AllowTweetVideo: true            # 是否允许视频推文
  AllowUserRegister: true          # 是否允许用户注册
  AllowPhoneBind: false             # 是否允许手机绑定
  DefaultTweetMaxLength: 2000      # 推文允许输入的最大长度， 默认2000字，值的范围需要查询后端支持的最大字数
  TweetWebEllipsisSize: 400        # Web端推文作为feed显示的最长字数，默认400字
  DefaultTweetVisibility: friend   # 推文默认可见性，默认好友可见 值: public/following/friend/private
  DefaultMsgLoopInterval: 5000     # 拉取未读消息的间隔，单位：毫秒, 默认5000ms 
  CopyrightTop: "精弘论坛"  # 顶部版权信息
  CopyrightLeft: "精弘网络"   # 左下角版权信息
  CopyrightLeftLink: "https://www.myzjut.org/index"  # 左下角版权信息链接
  CopyrightRight: "精弘网络" # 右下角版权信息
  CopyrightRightLink: "https://www.myzjut.org/index" # 右下角版权信息链接